### ISSUE TITLE
Cannot make 

### ISSUE THREAD

**Issue by gvsurenderreddy** [tempestsecurity/vpnbox#1]
secretbox.c:220:13: note: in expansion of macro ‘write_str’
             write_str(STDERR_FILENO, progname);
             ^
strannex.h:27:89: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     #define my_strlen(a)                   (((unsigned long long)rawmemchr(a, '\0')) - ((unsigned long long)a))
                                                                                         ^
strannex.h:32:61: note: in expansion of macro ‘my_strlen’
     #define write_str(fd,str)              write((fd),(str),my_strlen(str))
                                                             ^
secretbox.c:220:13: note: in expansion of macro ‘write_str’
             write_str(STDERR_FILENO, progname);
             ^
strannex.c: In function ‘write_int’:
strannex.c:87:5: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
     write(fd,str,size);
     ^
make: **\* [secretbox] Error 1

Can you please tell me how to build it please

**Comment by marcocarnut** [comment]
Hi,

It seems your compiler is turning warnings (as far as I can see harmless
ones) into fatal errors -- did you insert -Werror somewhere? Which version
of gcc are you using? I'll try
to reproduce your error here.

Here I can compile cleanly with gcc-4.4 and the Makefile provided.

-Marco.

**Comment by marcocarnut** [comment]
We just pushed changes to fix all compilation warnings and header inclusion problems. Could you please checkout and try again?

**Comment by gvsurenderreddy** [comment]
Thank you so much i was trying with GCC 5 now tried with 4.8 and it worked out fine .How do I make confutation settings and test can you please guide me

**Comment by marcocarnut** [comment]
Good to know that the build worked fine now.

Take a look at the Wiki: https://github.com/tempestsecurity/vpnbox/wiki

There you'll find a few recipes.

You will almost certainly need this as well: https://github.com/tempestsecurity/tsi-ucspi-udp

**Comment by gvsurenderreddy** [comment]
Its a great product thanks

**Comment by gvsurenderreddy** [comment]
Hello sir,
I have tried but i cannot ping I have no idea whats wrong
